resources:
  - name: goModAbsolutizerGit
    type: GitRepo
    configuration:
      path: jfrog/gomod-absolutizer
      branches:
        include: dev
      gitProvider: il_automation

pipelines:
  - name: Release
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: go
            versions:
              - "1.17"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: goModAbsolutizerGit
              trigger: false
          integrations:
            - name: il_automation
            - name: entplus_deployer
        execution:
          onExecute:
            - cd $res_goModAbsolutizerGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_BUILD_STATUS=PASS
            - export JFROG_CLI_BUILD_NAME=ecosystem-go-mod-abs-release
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Make sure version provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"

            # Configure Git and merge from the dev
            - git checkout master
            - git remote set-url origin https://$int_il_automation_token@github.com/jfrog/gomod-absolutizer.git
            - git merge origin/dev
            - git tag v${NEXT_VERSION}

            # Download JFrog CLI
            - curl -fL https://install-cli.jfrog.io | sh
            - jf c rm --quiet
            - jf c add internal --url=$int_entplus_deployer_url --user=$int_entplus_deployer_user --password=$int_entplus_deployer_apikey
            - jf goc --repo-resolve ecosys-go-virtual

            # Audit
            - jf audit

            # Upload build info
            - jf rt bag && jf rt bce
            - jf rt bp

            # Push to master
            - git clean -fd
            - git push
            - git push --tags

          onComplete:
            - jf c rm --quiet
